name = "WDL"
grammar = "wdl"
path_suffixes = ["wdl"]
line_comments = ["# "]
autoclose_before = ";:.,=}])"
tab_size = 4
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<<<", end = ">>>", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
