name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly
      - run: rustup component add rustfmt --toolchain nightly
      - run: cargo +nightly fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup target add wasm32-wasip1 --toolchain stable
      - run: cargo clippy --target wasm32-wasip1

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup target add wasm32-wasip1 --toolchain stable
      - run: cargo check --target wasm32-wasip1
